# Generated by Django 4.2.5 on 2023-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.TextField(default='6TeccdbwDLG_fbblLFsWolgoLy6vfFv54BVQwbDgCk0'),
        ),
        migrations.AddField(
            model_name='user',
            name='validated_email',
            field=models.BooleanField(default=False),
        ),
    ]
