# Generated by Django 4.2.5 on 2023-09-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_activation_token_user_validated_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.SlugField(default='FvsxU31FbDhA0UU6rRl-49Em0rQ-kYJSCV23Z2LkDvY', unique=True),
        ),
    ]
