# Generated by Django 4.2.5 on 2023-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.SlugField(default='uT1SqeNh3cyi2Tr71Hm6Z2yY6t0_ZX0w3IIdNcEnTis'),
        ),
    ]
