# Generated by Django 4.2.5 on 2023-09-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de projeto',
                'verbose_name_plural': 'Categorias de projeto',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('capa', models.ImageField(upload_to='projetos/%Y/%m')),
                ('descricao', models.CharField(max_length=255)),
                ('conteudo_capa', models.BooleanField(default=True)),
                ('conteudo', models.TextField()),
                ('visivel', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Em produção', 'Em produção'), ('Finalizado', 'Finalizado'), ('descontinuado', 'descontinuado')], default=('Em produção', 'Em produção'), max_length=255)),
                ('projeto_aplicado', models.BooleanField(default=False)),
                ('link_aplicacao', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.categoriaprojeto')),
            ],
        ),
    ]
