# Generated by Django 4.2.5 on 2023-09-16 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de projeto',
                'verbose_name_plural': 'Categorias de projeto',
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('status_projeto', models.CharField(choices=[('Pedido-recebido', 'Pedido recebido'), ('Em-negociação', 'Em negociação'), ('Em-produção', 'Em produção'), ('Finalizado', 'Finalizado'), ('descontinuado', 'descontinuado')], default=('Pedido-recebido', 'Pedido recebido'), max_length=255)),
                ('valor', models.FloatField(blank=True, default=0.0)),
                ('contrato', models.FileField(blank=True, null=True, upload_to='Trabalhos/%Y/%M')),
                ('assunto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.assunto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('capa', models.ImageField(upload_to='projetos/%Y/%m/')),
                ('descricao', models.CharField(max_length=255)),
                ('conteudo_capa', models.BooleanField(default=True, help_text='Este campo precisará estar marcado para exibir a capa nos detalhes do projeto')),
                ('conteudo', models.TextField()),
                ('visivel', models.BooleanField(default=True, help_text='Este campo precisará estar marcado para o projeto ser exibida publicamente')),
                ('status', models.CharField(choices=[('Em produção', 'Em produção'), ('Finalizado', 'Finalizado'), ('descontinuado', 'descontinuado')], default=('Em produção', 'Em produção'), max_length=255)),
                ('repositorio_link', models.URLField(default='https://github.com/Hericlys/')),
                ('projeto_aplicado', models.BooleanField(default=False, help_text='Este campo deve ser marcado apenas se hover uma aplicação a esse projeto.')),
                ('link_aplicacao', models.URLField(blank=True, help_text='Preencha esse campo apenas se hover uma aplicação para esse projeto.', null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.categoriaprojeto')),
            ],
        ),
    ]
