# Generated by Django 4.2.5 on 2023-09-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='repositorio_link',
            field=models.URLField(default='https://github.com/Hericlys/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='conteudo_capa',
            field=models.BooleanField(default=True, help_text='Este campo precisará estar marcado para exibir a capa nos detalhes do projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_aplicacao',
            field=models.URLField(blank=True, help_text='Preencha esse campo apenas se hover uma aplicação para esse projeto.', null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='projeto_aplicado',
            field=models.BooleanField(default=False, help_text='Este campo deve ser marcado apenas se hover uma aplicação a esse projeto.'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='visivel',
            field=models.BooleanField(default=True, help_text='Este campo precisará estar marcado para o projeto ser exibida publicamente'),
        ),
    ]
