# Generated by Django 4.2.5 on 2023-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projeto_repositorio_link_alter_projeto_conteudo_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(upload_to='projetos/%Y/%m/<django.db.models.fields.CharField>'),
        ),
    ]
