# Generated by Django 4.2.5 on 2023-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projeto_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(upload_to='projetos/%Y/%m/'),
        ),
    ]
